cabal-version:      3.0
name:               multitasking
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             simon
maintainer:         simre4775@gmail.com
-- copyright:
category:           Concurrency
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common common
    ghc-options: -Wall
    default-language: GHC2024
    build-depends:
        base ^>=4.21.0.0,
        stm

library
    import: common
    exposed-modules:
        Control.Concurrent.Multitasking
        Control.Concurrent.Multitasking.Task
        Control.Concurrent.Multitasking.Communication
    other-modules:
        Control.Concurrent.Multitasking.Coordinator
    build-depends:
        transformers,
        text,
        containers,
        unliftio,
        ki-unlifted
    -- other-extensions:
    hs-source-dirs:   src

test-suite multitasking-test
    import:           common
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        multitasking,
        tasty,
        tasty-bench,
        tasty-hunit
